### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [ZijingPeng/leaflet-tooltip-layout#1]
Hi,

I notice this project is currently listed as release 0.1.1 at https://www.npmjs.com/package/leaflet-tooltip-layout but lack a formal release tag here on Github.

Please tag releases, to ease tracking source - e.g. for (re)distributors (I consider packaging this exciting project officially for Debian).

**Comment by ZijingPeng** [comment]
> Hi,
> 
> I notice this project is currently listed as release 0.1.1 at https://www.npmjs.com/package/leaflet-tooltip-layout but lack a formal release tag here on Github.
> 
> Please tag releases, to ease tracking source - e.g. for (re)distributors (I consider packaging this exciting project officially for Debian).

Thanks!
